plugins {
    id 'java'
    id 'xyz.wagyourtail.unimined' version '1.4.17-kappa'
}

group = 'com.apocollis.aqtweaks'
version = '1.6'
base {
    archivesName.set('ArcanaQuestTweaks')
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    modCompileOnly
    compileOnly.extendsFrom(modCompileOnly)
}

unimined.minecraft {
    version '1.12.2'

    mappings {
        mcp('stable', '39-1.12')
    }

    cleanroom {
        loader('0.5.7-alpha')
    }

    defaultRemapJar = true
}

repositories {
    mavenCentral()
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    fileTree(dir: 'libs', include: ['*.jar']).each { jar ->
        modCompileOnly files(jar)
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes([
            "Specification-Title": "aqtweaks",
            "Specification-Vendor": "apocollis",
            "Specification-Version": "1",
            "Implementation-Title": project.name,
            "Implementation-Version": "${version}",
            "Implementation-Vendor" :"apocollis",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "ModType": "CRL",
            "FMLCorePluginContainsFMLMod": "true",
            "ForceLoadAsMod": "true"
        ])
    }
}